### ISSUE TITLE
Error [TypeError]: Cannot read property 'Location' of undefined

### ISSUE THREAD

**Issue by prasannavsa** [midudev/s3-folder-upload#19]
Error [TypeError]: Cannot read property 'Location' of undefined

**Comment by pkpbynum** [comment]
Hi there, I just ran into this and it was an error in the credentials I was passing--I wasn't passing the region!

**Comment by prasannavsa** [comment]
I am using the correct credentials with the region, but still has an issue

**Comment by midudev** [comment]
Hey @prasannavsa. Which method are you using to pass credentials? Are you using the CLI or the programmatic package? Any details you could provide, could help to solve this.

**Comment by DanielBalog86** [comment]
I'm having the same issue. I'm using s3FolderUpload like such:

```
const awsCredentials = {
  accessKeyId: process.env.AWS_ACCESS_ID,
  secretAccessKey: process.env.AWS_SECRET_KEY,
  region: process.env.AWS_REGION,
  bucket: process.env.AWS_BUCKET,
};

s3FolderUpload(directoryToUpload, awsCredentials, {
    useFoldersForFileTypes: false,
    useIAMRoleCredentials: false,
    uploadFolder: awsBucketOutputFolder,
  });
```

All of the credentials are filled in and correct.

The stack is as follows:
```
Error [TypeError]: Cannot read property 'Location' of undefined
    at ManagedUpload.onUpload [as callback] (/Users/user/project/test/scripts/node_modules/s3-folder-upload/lib/aws-s3.js:43:23)
    at Response.finishSinglePart (/Users/user/project/test/scripts/node_modules/s3-folder-upload/node_modules/aws-sdk/lib/s3/managed_upload.js:674:28)
    at Request.<anonymous> (/Users/user/project/test/scripts/node_modules/s3-folder-upload/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/user/project/test/scripts/node_modules/s3-folder-upload/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/user/project/test/scripts/node_modules/s3-folder-upload/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/user/project/test/scripts/node_modules/s3-folder-upload/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/user/project/test/scripts/node_modules/s3-folder-upload/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/user/project/test/scripts/node_modules/s3-folder-upload/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/user/project/test/scripts/node_modules/s3-folder-upload/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/user/project/test/scripts/node_modules/s3-folder-upload/node_modules/aws-sdk/lib/request.js:38:9) {
  code: 'TypeError',
  time: 2020-12-10T13:48:27.934Z
}
error Command failed with exit code 1.
```

It seems that aws-s3.js calls `undefined` for the `data` argument of `onUpload`.

Any idea what might be causing this? I have the feeling something else went wrong in the upload process and this is just an unhandled error. Perhaps permissions?

**Comment by DanielBalog86** [comment]
Created a small pull request that patches at least the TypeError. It was because done was called twice when there is an error.

This now gives me a PermissionDenied error instead, which is a step in the right direction. But these credentials do work when I use the `aws-cli` tool, so not sure what could still be wrong.

**Comment by DanielBalog86** [comment]
Ok I think I might have found something.

So further investigation revealed that I could only use `s3-folder-upload` if in the bucket settings I set "Block public access" off. But for my use-case, I need to have this on. Only private authenticated uploads should be allowed for security reasons.

By default, it seems `aws-s3.js` the `DEFAULT_ACL` is `public_read` (line 12).

Is this correct? Should the default not be something like `private` by default?

In any case, if I change it to `private` locally, I no longer get PermissionDenied errors.

**Comment by DanielBalog86** [comment]
So I understand that I can set `ACL:"private" ` as an option when calling s3-folder-upload, and then my problem is solved, like so:

```js
s3FolderUpload(directoryToUpload, awsCredentials, {
    useFoldersForFileTypes: false,
    useIAMRoleCredentials: false,
    uploadFolder: awsBucketOutputFolder,
    ACL: "private"
  });
```

I do think this would be a better default though. But for me the issue is fixed :-) I hope someone else finds this in the future.

EDIT: "private" is actually the default according to this: https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl . So this is basically a mismatch between AWS and s3-folder-upload.
